shop/miniapp/urls.py
from django.urls import path
from .views import test_view, ProductDetailView

urlpatterns = [
    path('', test_view, name='base'),
    path('products/<str:ct_model>/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('miniapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/miniapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.urls import reverse

User = get_user_model()


def get_models_for_count(*model_names):
    return [models.Count(model_name) for model_name in model_names]


def get_product_url(odj, viewname):
    ct_model = obj.__class__._meta.model_name
    return reverse(viewname, kwargs={'ct_model': ct_model, 'slug': obj.slug})


class MinResolutionErrorException(Exception):
    pass


class MaxResolutionErrorException(Exception):
    pass


class LatestProductsManager:
    @staticmethod
    def get_products_for_main_page(*args, **kwargs):
        with_respect_to = kwargs.get('with_respect_to')
        products = []
        ct_models = ContentType.objects.filter(model_in=args)
        for ct_models in ct_models:
            model_products = ct_models.model_class()._base_manager.all().order_by('id')[:5]
            products.extend(model_products)
        if with_respect_to:
            ct_models = ContentType.objects.filter(models=with_respect_to)
            if ct_models.exists():
                if with_respect_to in args:
                    return sorted(
                        products, key=lambda x: x.__class__._meta.model_name.startswith(with_respect_to), reverse=True
                    )
        return products


class LatestProducts:
    objects = LatestProductsManager()


class CategoryManager(models.Manager):

    CATEGORY_NAME_COUNT_NAME = {
        'Notebooks': 'notebook__count',
        'Smartphone': 'smartphone__count',
    }

    def get_queryset(self):
        return super().get_queryset()

    def get_categories_for_left_sidebar(self):
        models = get_models_for_count('notebook', 'smartphone')
        qs = list(self.get_queryset().annotate(*models).values())
        return [dict(name=c['name'], slug=c['slug'], count=c[self.CATEGORY_NAME_COUNT_NAME[c['name']]]) for c in qs]


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Имя категории')
    slug = models.SlugField(unique=True)
    objects = CategoryManager()

    def __str__(self):
        return self.name


class Product(models.Model):
    class Meta:
        abstract = True

    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name='Наименование')
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name='Изображение')
    description = models.TextField(verbose_name='Описание товара', null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')

    def __str__(self):
        return self.title


class Notebook(Product):
    diagonal = models.CharField(max_length=255, verbose_name='Диаганаль')
    display_type = models.CharField(max_length=255, verbose_name='Тип дисплея')
    processor_freq = models.CharField(max_length=255, verbose_name='Частота процессора')
    ram = models.CharField(max_length=255, verbose_name='Оперативная память')
    video = models.CharField(max_length=255, verbose_name='Видеокарта')
    time_without_charge = models.CharField(max_length=255, verbose_name='Время работы')

    def __str__(self):
        return "{} : {} ".format(self.category.name, self.title)

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')


class Smartphone(Product):
    diagonal = models.CharField(max_length=255, verbose_name='Диаганаль')
    display_type = models.CharField(max_length=255, verbose_name='Тип дисплея')
    resolution = models.CharField(max_length=255, verbose_name='Разрешение экрана')
    accum_volume = models.CharField(max_length=255, verbose_name='Емкость батареи')
    ram = models.CharField(max_length=255, verbose_name='Оперативная память')
    sd = models.BooleanField(default=True, verbose_name='Наличие SD карты')
    sd_volume_max = models.CharField(max_length=255, null=True, blank=True, verbose_name='Объем памяти мах.')
    mini_cam_mp = models.CharField(max_length=255, verbose_name='Камера Главная')
    frontal_cam_mp = models.CharField(max_length=255, verbose_name='Фронтальная камера')

    def __str__(self):
        return "{} : {} ".format(self.category.name, self.title)

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')

    # @property
    # def sd(self):
    #     if self.sd:
    #         return 'ДА'
    #     return 'НЕТ'


class CartProduct(models.Model):
    user = models.ForeignKey('Customer', verbose_name='Покупатель', on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_products')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена')

    def __str__(self):
        return "Продукт: {}(Для корзины)".format(self.content_object.title)


class Cart(models.Model):
    owner = models.ForeignKey('Customer', verbose_name='Покуатель', on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
    total_product = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена')
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)


class Customer(models.Model):
    user = models.ForeignKey(User, verbose_name='пользователь', on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, verbose_name='Номер телефона')
    address = models.CharField(max_length=255, verbose_name='Адрес')

    def __str__(self):
        return "Покупатель: {} {}".format(self.user.first_name, self.user.last_name)


class SomeModel(models.Model):
    image = models.ImageField()

    def __str__(self):
        return str(self.id)

shop/miniapp/views.py
from django.shortcuts import render
from django.views.generic import DetailView

from .models import Notebook, Smartphone, Category


def test_view(request):
    categories = Category.objects.get_categories_for_left_sidebar()
    return render(request, 'base.html', {'categories': categories})


class ProductDetailView(DetailView):

    CT_MODEL_MODEL_CLASS = {
        'notebook':  Notebook,
        'smartphone': Smartphone,
    }

    def dispatch(self, request, *args, **kwargs):
        self.model = self.CT_MODEL_MODEL_CLASS[kwargs['ct_model']]
        self.queryset = self.model._base_manager.all()
        return super().dispatch(request, *args, **kwargs)

    context_object_name = 'product'
    template_name = 'product_detail.html'
    slug_url_kwarg = 'slug'

shop/miniapp/templates/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script>
(function($) {
    $('#id_sd').on('click', function(){
        if($('#id_sd').prop('checked') == true){
            $('#id_sd_volume_max').prop('readonly', false)
            $('#id_sd_volume_max').val('')
            $('#id_sd_volume_max').css('background','gray')
        }else{
            $('#id_sd_volume_max').prop('readonly', true)
            $('#id_sd_volume_max').val('')
            $('#id_sd_volume_max').css('background', 'lightgray')
        }
    })
})(django.jQuery);
</script>
{% endblock %}

shop/miniapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Shop Homepage - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico"/>
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="css/styles.css" rel="stylesheet"/>
</head>
<body>
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{%url 'base'%}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Contacts</a></li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        </li>
                        {% for category in categories %}
                        <li><a class="dropdown-item" href="#!">{{ category.name }} {{category.count}}</a></li>
                        {% endfor %}

                    </ul>
                </li>
            </ul>
            <form class="d-flex">
                <button class="btn btn-outline-dark" type="submit">
                    <i class="bi-cart-fill me-1"></i>
                    Cart
                    <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                </button>
            </form>
        </div>
    </div>
</nav>
<!-- Header-->
<header class="bg-dark py-1">
    <div class="container px-4 px-lg-1 my-1">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">My Shop</h1>
            <p class="lead fw-normal text-white-40 mb-0">In developing</p>
        </div>
    </div>
</header>
<!-- Section-->
{% block content %}

{% endblock %}
<!-- Footer-->
<footer class="py-3 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
<!-- Core theme JS-->
<script src="js/scripts.js"></script>
</body>
</html>

shop/miniapp/templates/notebook_specification.html
<table class="table">
    <tbody>
    <tr>
        <td>Частота процессора</td>
        <td>{{ product.processor_freq}}</td>
    </tr>
    <tr>
        <td>Диагональ</td>
        <td>{{ product.diagonal }}</td>
    </tr>
    <tr>
        <td>Тип дисплея</td>
        <td>{{ product.display_type }}</td>
    </tr>
    <tr>
        <td>Оперативная память</td>
        <td>{{ product.ram}}</td>
    </tr>
    <tr>
        <td>Видеокарта</td>
        <td>{{product.video}}</td>
    </tr>
    <tr>
        <td>Время работы</td>
        <td>{{product.time_without_charge}}</td>
    </tr>
    </tbody>
</table>
</body>
</html>

shop/miniapp/templates/product_detail.html
{% extends 'base.html' %}
{% load specifications %}
{% block content %}
<nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{%url 'base'%}">Главная</a></li>
        <li class="breadcrumb-item"><a href="#">{{ product.category.name }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ product.title }}</li>
    </ol>
</nav>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <img src="{{ product.image.url }}" class="mt-4">
        </div>
        <div class="col-md-3">
            <h4>{{ product.title}}</h4>
            <p>Цена: {{ product.price }} руб.<p>
            <p>Описание: {{ product.description }}</p>
        </div>
            <p class=mt-4>Характеристики: </p>

        {{ product|product_spec  }}


<!--второй способ получения характеристи-->

<!--        {% if product.category.slug == 'smartphone' %}-->
<!--            {% include 'smartphone_specification.html' %}-->
<!--        {% else %}-->
<!--            {% include 'notebook_specification.html' %}-->
<!--        {% endif %}-->

    </div>
</div>
{% endblock %}

shop/miniapp/templates/smartphone_specification.html
<table class="table">
    <tbody>
    <tr>
        <td>Диагональ</td>
        <td>{{ product.diagonal }}</td>
    </tr>
    <tr>
        <td>Тип дисплея</td>
        <td>{{ product.display_type }}</td>
    </tr>
    <tr>
        <td>Разрешение экрана</td>
        <td>{{ product.resolution}}</td>
    </tr>
    <tr>
        <td>Емкость батареи</td>
        <td>{{ product.accum_volume}}</td>
    </tr>
    <tr>
        <td>Оперативная память</td>
        <td>{{ product.ram}}</td>
    </tr>
    <tr>
        <td>Наличи слота памяти</td>
        <td>{{ product.sd}}</td>
    </tr>
    <tr>
        <td>Обьем памяти</td>
        <td>{{ product.sd_volume_max}}</td>
    </tr>
            <tr>
        <td>Камера Главная</td>
        <td>{{ product.mini_cam_mp}}</td>
    </tr>
    <tr>
        <td>Фронтальная камера</td>
        <td>{{ product.frontal_cam_mp}}</td>
    </tr>
    </tbody>
</table>